language: julia
os:
  - linux
before_install:
  sudo apt-get install libgtk-3-0
julia:
  - 0.6
  - nightly
notifications:
  email: false
matrix:
  allow_failures:
    - julia: nightly
addons:
  apt:
    packages:
      - imagemagick
      - tcl8.5
      - tk8.5
      - libcairo2
      - libavcodec-extra
      - libavdevice-dev
      - libavfilter-dev
      - libavformat-dev
      - libavutil-dev
      - libswscale-dev
      - xvfb
      - xauth
      - libgtk-3-0
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - if [[ `uname` = "Linux" ]]; then TESTCMD="xvfb-run julia"; else TESTCMD="julia"; fi
  - $TESTCMD --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.test("SensorFeatureTracking"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("SensorFeatureTracking")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - $TESTCMD -e 'cd(Pkg.dir("SensorFeatureTracking")); include(joinpath("docs", "make.jl"))'
